#!/usr/bin/env ruby

require_relative '../shared/common.rb'

# uptd is short form of "uptodate".
#
# Often a branch falls behind master and it needs to be brough uptodate
# so that the branch has all the commits from master.
#
# One way to do that is to do git rebase master. This script makes that
# process much easier by. This script does following things.
#
# - switch to master
# - gets the latest master
# - switch back to the branch
# - git rebase master
# - push the branch to github
#
# Usage :
#
# stand in a branch and execute uptd
#

class DeployReady

  def process
    current_branch_name = Util.new.branch_name
    update_current_branch
    update_master
    merge_master_to_current_branch(current_branch_name) unless current_branch_name == 'master'
  end

  private

  def update_master
    execute_cmd 'git checkout master'
    execute_cmd 'git pull'
  end

  def merge_master_to_current_branch branch_name
    execute_cmd "git checkout #{branch_name}"
    execute_cmd 'git merge master'
    execute_cmd 'git push'
  end

  def update_current_branch
    execute_cmd 'git pull'
  end

end

DeployReady.new.process
