#!/usr/bin/env ruby

require_relative '../shared/common.rb'

# Sometimes I need empty commit to see if continuous integration is working or not. Or to test git hooks.
#
# Usage:
#
# Stand in the branch for which you want to send pull request and execute git_empty_commit .
#

cmd =  %Q{git commit -m 'empty commit' --allow-empty}
execute_cmd cmd
