#!/usr/bin/env ruby

require_relative '../shared/common.rb'

# this script
# - gets the latest master
# - merges master to the current branch
# - push the branch to github
# - pushes for deployment
#
# Usage :
# stand in a branch and execute mdeploy
#


def deploy
  execute_cmd "bundle install"
  execute_cmd "bundle exec cap #{branch_name} deploy"
end


execute_cmd "uptd"
deploy

