#!/usr/bin/env ruby

require_relative '../common.rb'

# uptd is short form of "uptodate".
#
# Often a branch falls behind master and it needs to be brough uptodate
# so that the branch has all the commits from master.
#
# One way to do that is to do git rebase master. This script makes that
# process much easier by. This script does following things.
#
# - switch to master
# - gets the latest master
# - switch back to the branch
# - git rebase master
# - push the branch to github
#
# Usage :
#
# stand in a branch and execute uptd
#

def update_master
  execute_cmd 'git checkout master'
  execute_cmd 'git pull'
end

def rebase_current_branch branch_name
  execute_cmd "git checkout #{branch_name}"
  execute_cmd 'git rebase master'
  execute_cmd 'git push'
end

def update_current_branch
  execute_cmd 'git pull'
end

current_branch_name = branch_name

update_current_branch
update_master
rebase_current_branch(current_branch_name) unless current_branch_name == 'master'

